spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobtracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "change-this-secret-key-change-this-secret-key-123456"
    expiration-ms: 86400000

server:
  port: 8080
